### PR TITLE
ENGOPS-1553 Retry if UNKNOWN PRs exceed threshold

### PR DESCRIPTION
**Pull request by jrimmer-housecallpro**
When you make a change to a branch, especially the target branch, all branches' merge states become UNKNOWN. This usually resolves itself quickly. This version now retries with a delay in this case.

### CODE REVIEW

**Review by dannycastillo — APPROVED** [review]

**Review by crwilson — APPROVED** [review]
I _think_ this LGTM. But my ruby-foo is weak.

**Review by emj-io — APPROVED** [review]
Not being able to test this without merging to master feels like a smell, but probably not one we're going to fix in the short term.

**Comment by jrimmer-housecallpro** [comment]
> I _think_ this LGTM. But my ruby-foo is weak.

I think so, too, but I need to test it locally ... once something is merged to master. Such as the ENGOPS-1632 PR :D

**Comment by jrimmer-housecallpro** [comment]
> Not being able to test this without merging to master feels like a smell, but probably not one we're going to fix in the short term.

To be clear, it's not that THIS needs to be merged to master to test. It's that something else needs to be merged to master on hcw to test this. :)

**Comment by jrimmer-housecallpro** [comment]
It works. But let's go with 1%, not 10%, as the default.

**Pull request merged**
